"""
Integration tests for the HTTP interface layer — health and docs endpoints.

AC covered:
  - Given the app is started with uvicorn dark_factory.main:app,
    when GET /docs is requested, then HTTP 200 is returned
  - Given a clean clone, when uv sync runs, then all packages install and exit 0
    (tested indirectly: the fixture can construct create_app())

I/O & Edge-Case Matrix rows covered:
  - App cold start, default env: No .env file; Settings.usgs_base_url has default;
    create_app() returns FastAPI instance; /docs -> HTTP 200
  - Settings missing required var: pydantic ValidationError raised at startup
    (tested via monkeypatching the environment)

TDD phase: RED — will fail with ImportError until main.py / config.py are created.
"""

from __future__ import annotations

import os

import pytest


class TestHealthEndpoint:
    """
    Given: the app is started with default settings (no .env file)
    When:  GET /health is requested via ASGITransport
    Then:  HTTP 200 is returned with {"status": "ok"}
    """

    @pytest.mark.anyio
    async def test_health_returns_200(self) -> None:
        """
        Given: create_app() is called with default Settings
        When:  GET /health is requested
        Then:  response status code is 200
        """
        import httpx
        from httpx import ASGITransport, AsyncClient

        from dark_factory.main import create_app  # ImportError until impl exists

        app = create_app()
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://testserver") as client:
            response = await client.get("/health")

        assert response.status_code == 200

    @pytest.mark.anyio
    async def test_health_returns_status_ok_body(self) -> None:
        """
        Given: create_app() is called with default Settings
        When:  GET /health is requested
        Then:  response JSON body contains {"status": "ok"}
        """
        import httpx
        from httpx import ASGITransport, AsyncClient

        from dark_factory.main import create_app

        app = create_app()
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://testserver") as client:
            response = await client.get("/health")

        assert response.json() == {"status": "ok"}

    @pytest.mark.anyio
    async def test_create_app_returns_fastapi_instance(self) -> None:
        """
        Given: no .env file present and Settings.usgs_base_url has a default
        When:  create_app() is called
        Then:  the return value is a FastAPI application instance
        """
        from fastapi import FastAPI

        from dark_factory.main import create_app

        app = create_app()
        assert isinstance(app, FastAPI)


class TestDocsEndpoint:
    """
    Given: the app is started with default settings
    When:  GET /docs is requested
    Then:  HTTP 200 is returned (Swagger UI auto-generated by FastAPI)
    """

    @pytest.mark.anyio
    async def test_docs_returns_200(self) -> None:
        """
        Given: create_app() with defaults
        When:  GET /docs is requested via ASGITransport
        Then:  response status code is 200
        """
        from httpx import ASGITransport, AsyncClient

        from dark_factory.main import create_app

        app = create_app()
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://testserver") as client:
            response = await client.get("/docs")

        assert response.status_code == 200


class TestSettingsConfig:
    """
    Tests for dark_factory.config.Settings (pydantic-settings).

    I/O & Edge-Case Matrix — "Settings missing required var" row:
      Given: a required env var is absent with no default
      When:  Settings() is constructed
      Then:  pydantic ValidationError is raised

    I/O & Edge-Case Matrix — "App cold start, default env" row:
      Given: no .env file; usgs_base_url has a default
      When:  Settings() is constructed
      Then:  settings.usgs_base_url returns the USGS default URL
    """

    def test_settings_can_be_imported(self) -> None:
        from dark_factory.config import Settings  # noqa: F401  # ImportError until impl

    def test_settings_has_default_usgs_base_url(self) -> None:
        """
        Given: no environment override for USGS_BASE_URL
        When:  Settings() is instantiated
        Then:  usgs_base_url is the public USGS endpoint
        """
        # Ensure no override leaks from the environment during tests
        env_backup = os.environ.pop("USGS_BASE_URL", None)
        try:
            from dark_factory.config import Settings

            settings = Settings()
            assert settings.usgs_base_url == "https://earthquake.usgs.gov/fdsnws/event/1/"
        finally:
            if env_backup is not None:
                os.environ["USGS_BASE_URL"] = env_backup

    def test_settings_env_var_overrides_default(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """
        Given: a .env / env var with USGS_BASE_URL overriding the default
        When:  Settings() is called
        Then:  the overridden value is returned by settings.usgs_base_url
        """
        custom_url = "https://mock-usgs.example.com/query"
        monkeypatch.setenv("USGS_BASE_URL", custom_url)

        # Re-import to pick up env change (pydantic-settings reads at construction time)
        from dark_factory.config import Settings

        settings = Settings()
        assert settings.usgs_base_url == custom_url
